### ISSUE TITLE
Добавлять медикам 2 очка за возрождение

### ISSUE THREAD

**Issue by tym32167** [TEHGAM/RW2#288]
Необходимо доработать систему лечения/поднятия игроков - медику, который поднимает раненого, нужно добавить 2 очка. 
Это было реализовано уже в [старой версии миссии](https://github.com/TEHGAM/RW2/tree/master/co40_Invade_Annex_2_75b.Altis/scripts/%3DBTC%3D_revive)

У самого времени не хватает, нужна помощь. Это задача с низким приоритетом.

**Comment by Noart537** [comment]
Исправление нашел. Скоро обновлю миссию. Только там +1. Исправлю на +2 и выложу.
https://drive.google.com/file/d/0B_FkN9Mg8MBqWTlTdVNPa3NtMk0/view?usp=sharing

**Comment by Tourorist** [comment]
@Noart537, обрадовал!
Как мне кажется, поощрение работы вспомогательных классов — как эта самая конфетка медикам за поднятие своих — служит хорошим стимулом подвигающим игроков на более слаженную командную игру. Это относительно, по крайне мере, игроков вроде меня, которые используют статистику как планку для сравнения качества своей и чужой игры.

В противовес этому, что касается кнутов (снятия очков), то их пока и так хватает с одних только убийств (TK) и уничтожения собственной техники, которые встречаются и среди опытных игроков.

В будущем, можно еще будет подумать о поощрении работы механиков, как в той же Доминации.

**Comment by Noart537** [comment]
Не могу найти где параметр на +2 нужно изменить. Если кто знает помогайте).
