### ISSUE TITLE
Обновить используемые скрипты

### ISSUE THREAD

**Issue by Tourorist** [TEHGAM/RW2#290]
Я пару заметил когда ковырялся с авторством нашей сборки, примеров может быть больше:
* [Repetitive Cleanup](https://github.com/TEHGAM/RW2/blob/master/co40_Invade_Annex_2_77.Altis/scripts/cleanup/repetitive_cleanup.sqf) – у нас версия 1.7, хотя уже есть [1.9](https://github.com/aeroson/a3-misc/blob/master/repetitive_cleanup.sqf).
* [TAW View Distance Script](https://github.com/TEHGAM/RW2/tree/master/co40_Invade_Annex_2_77.Altis/scripts/taw_vd) – у нас версия 1.3, а у Tonic-а уже вышла [1.4](http://www.armaholic.com/page.php?id=19751).

И еще вопрос. Мы используем меню отрядов от [Xeno](https://github.com/TEHGAM/RW2/tree/f11a0b1b69f72fd6e050444c4c9494332577fb81/co40_Invade_Annex_2_77.Altis/scripts/DOM_squad) или от [aeroson](https://github.com/TEHGAM/RW2/blob/master/co40_Invade_Annex_2_77.Altis/scripts/group_manager.sqf)-а? Зачем нам оба эти скрипта, или это разные вещи?

**Comment by Noart537** [comment]
Repetitive Cleanup Ставил, он примерно раз в 5 минут чистит всю брошенную экипировку, с объектами - миномет, пулемет пока не проверял. Ставить?

**Comment by tym32167** [comment]
Ставь

**Comment by tym32167** [comment]
@Noart537  TAW View Distance Script тоже обновил?

**Comment by Noart537** [comment]
Да. Обновление скрипта прорисовки. https://github.com/TEHGAM/RW2/commit/b54661bf8c0ba072cdfb9ab4a1e9b6e4fa2ba266

**Comment by tym32167** [comment]
@Noart537 принял.
