### ISSUE TITLE
Необходимо обновить игровые правила в миссии

### ISSUE THREAD

**Issue by tym32167** [TEHGAM/RW2#291]
## Правила
Необходимо обновить [*игровые правила в миссии*](https://github.com/TEHGAM/RW2/blob/master/Annex_Done_Right.Altis/scripts/misc/diary.sqf) на [*самые актуальные*](http://tehgam.com/viewtopic.php?f=11&t=5&p=5#p5). Естественно, речь идет только об основных правилах. Миньки, Элитки и Варфарные правила в миссию вносить не нужно.

@Tourorist, у тебя уже есть опыт работы с бисовским диалектом HTML, потому назначил на тебя.

**Comment by Tourorist** [comment]
**Готово:**
![](https://raw.githubusercontent.com/TEHGAM/Docs/master/images/adr/ingame-rules.png)

Каждый из элементов правил — [заголовок](https://github.com/TEHGAM/RW2/issues/292#issuecomment-71819183), содержание, примечание — имеет собственный размер и цвет шрифта, посредством чего мы обращаем внимание читающего на значимость.

**Comment by Tourorist** [comment]
Заодно поправил оформления нашей страницы и поменял её местами с Ahoy-цами, чтобы наша была внизу — так-как нижняя всегда открывается первой. :smile:
![](https://raw.githubusercontent.com/TEHGAM/Docs/master/images/adr/ingame-credits.png)

**Comment by tym32167** [comment]
Красотень :smile:

**Comment by Noart537** [comment]
<img src=http://arcanumclub.ru/smiles/smile9.gif>

**Comment by Tourorist** [comment]
Я так понимаю все довольны и конечно же всё полностью проверили. :smile:

Ладно, закрываю эту задачу в отношении к <kbd>v3.5</kbd>. Если в будущем нужно будет опять залатать, то откроем заново и обсудим.
