### ISSUE TITLE
Необходимо обновить игровые правила в вики

### ISSUE THREAD

**Issue by tym32167** [TEHGAM/RW2#292]
Задача аналогичная #291, только обновить нужно [Вики](https://github.com/TEHGAM/RW2/wiki/RW:-%D0%9F%D1%80%D0%B0%D0%B2%D0%B8%D0%BB%D0%B0) нашего проекта.

**Comment by Tourorist** [comment]
Так как у Правил в нашей вики и у документа на общей репке разный формат (MD v. HTML), то пришлось править в ручную и параллельно в трёх местах — [Docs](https://github.com/TEHGAM/Docs/blob/master/Game_Rules.md), [Правила](https://github.com/TEHGAM/RW2/wiki/RW:-%D0%9F%D1%80%D0%B0%D0%B2%D0%B8%D0%BB%D0%B0) / [Rules](https://github.com/TEHGAM/RW2/wiki/RW:-Rules) — вроде как теперь везде содержание пока что одинаковое.

Если хотите, можете проверить если там вдруг что не так, а вечером я уже буду переносить их в игровой журнал.

**Comment by Tourorist** [comment]
Чуток доработал оформление, разбив некоторые из параграфов на части, так чтобы вступительная (основная) часть была короче и служила как заголовок правила.

**Comment by Tourorist** [comment]
Поправил английскую версию соответствующим образом.

**Comment by a11archer** [comment]
Проверил английскую версию.

**Comment by Tourorist** [comment]
Вот и ладушки. Закрываю задачу.
