### ISSUE TITLE
Конфликт скриптов сохранения снаряжения

### ISSUE THREAD

**Issue by PR9INICHEK** [TEHGAM/RW2#293]
**BTC Revive** имеет функцию сохранения текущего снаряжения и загрузку оного после смерти, но с некоторыми ошибками и недочётами. После возрождения у вас будет столько же оружия и боеприпасов, сколько было до смерти, а не сколько вы брали на базе.

**VAS** имеет те же функции сохранения нужного снаряжения в ячейку и если нажать единожды на базе кнопку «загружать при», то оно будет всегда в таком состоянии загружаться после смерти или поднятия вас медиком.

Так вот, на сервере оба эти параметра включены. Угадайте, какие ошибки они собой порождают?

**Есть много путей решения:**
 1. Отключить функцию сохранения у BTC Revive и научить новичков сохранять снаряжение в VAS
 2. Дописать функцию у BTC Revive и пользоваться только им
 3. Сделать кнопку «Сохранить снаряжение» и пользоваться только ею, при этом обязательно отключить функции у остальных (VAS и BTC). C этой же кнопкой VAS можно полностью убрать и пользоваться BIS-овским прекрасным арсеналом.

**Comment by Noart537** [comment]
У кого есть время, гляньте http://forums.bistudio.com/showthread.php?148577-GET-SET-Loadout-(saves-and-loads-pretty-much-everything)

**Comment by tym32167** [comment]
@Noart537 Я думаю, вкручивание ещё одного скрипта в это дело только усложнит всё. Это как в анекдоте - у нас было 2 скрипта и 2 проблемы. Мы добавили ещё 1 скрипт, чтобы всё заработало. Теперь у нас 3 проблемы.

**Comment by Noart537** [comment]
Ну можно же удалить первые два, если они не работают.

**Comment by a11archer** [comment]
Предлагаю решение закоментить в =BTC=_functions.sqf тело функцию BTC_set_gear через /* и */ как прочие секции. Проверить. щас пулл запрос сделаю.

**Comment by a11archer** [comment]
У меня теперь не работает сетевая игра (блокировка на уровне прокси стоит) я сам не могу проверить. Нужен кто-то кто может помочь результат оценить. Вызовет ли это ошибки. По идее не должно.

**Comment by Noart537** [comment]
Вечером смогу проверить. В ТСке буду.

**Comment by a11archer** [comment]
Опечатка. закоментировать надо то что внутри этой функции а не саму функцию. Вообщем все вроде бы просто но проверять надо на сервере, а ради этого тестовый сервер разворачивать глупо. Давайте на резервном сразу ставить как только поправлю?

**Comment by tym32167** [comment]
На тестовом всё равно надо проверять, так как второй сервер часто перегружать - плохая идея, а доступ у нас есть только ко второму.

**Comment by a11archer** [comment]
Я имею в виду reserved Tehgam2: все равно чисто логически решение найдено и оно правильное.

**Comment by tym32167** [comment]
Я ж говорю, у меня доступа туда нет, там только Рико рулит :)

**Comment by a11archer** [comment]
Если я обезглавлю систему btc как по пункту 1)
в Арсенале как и в и VTS Ammobox есть функции загрузки снаряжения по умолчанию при смерти. ничего не добавляется кроме двух кавычек. Буду править.

**Comment by a11archer** [comment]
В линуксе на веб интерфейсе в репозитории не сохраняется .sqf файл . придется мне завтра в windows клиенте gihHub for windows добавить кавычки эти. В главную ветку сохраню.

**Comment by a11archer** [comment]
Заменил.

**Comment by a11archer** [comment]
для проверки запущен
TEHGAM 2 Test Server (www.TEHGAM.com)
пароль единичка

**Comment by a11archer** [comment]
я проверял - грузится VAS снаряжение по умолчанию без проблем. Если не загружать по умолчанию то грузится снаряжение при заходе на сервер как договаривались.
