### ISSUE TITLE
Укоротить все возможные сообщения

### ISSUE THREAD

**Issue by Tourorist** [TEHGAM/RW2#306]
Раз уж они есть и привлекают внимание—или больше отвлекают своим многословием — то, думаю нужно использовать их как возможность проинструктировать игрока по конкретным задачам. То есть, ограничить их содержание практической информацией вместо имеющихся фоновых повествований — формат оригинала, перешедший с переводом.

В контексте 2-ого (миссии с подвижными задачами) эти рассказы читаются не более чем как субъективные заметки. Единственная сказка имеющая отношения к событиям в игре это то, что мы в двустороннем конфликте на фоне населённой местности, что и задаёт порядок ведения боя—мочи всех ботов кроме гражданских. Допки, основы — одна на другой. Вышел, зашёл — всё мелькает. Сюжет хоть в космос перемести, на игру особо не повлияет.

Другое дело одиночные игры, которые, в лучших случаях, ради этих самых историй и играют. Да, наверное и в статических PvP миссиях, вроде тех что делает Валка, предыстории служат свою роль, как прибор для тактической рационализации целей. Например, таким образом что, нарвавшись час-полтора спустя на первого врага ты не думаешь как бы побыстрей его трахнуть да смыться, а просчитываешь что данное столкновение даст и как повлияет на общий ход событий — ввиду совокупности поставленных задач и летальности любого падения. Поэтому, что-да-как там конечно имеет смысл прописать заранее. Нам же, это не нужно.

#### К примеру:
![](https://raw.githubusercontent.com/Tourorist/TPS/master/rw2/ra-main.jpg)
* Первое предложение к чертям! У нас нет ни какой системы вознаграждения за основу, чтобы там какое-то командование (как в Зевсе) нас на практике поощряло новыми возможностями или предметами. Где пряники раздают, как при допзаданиях, там конечно подобные сообщения имеют смысл для напоминания того что экстра-хлам дают только за успешное выполнение поставленных задач.

* Второе еще ладно. Напоминание что отдельным игрокам следует поправить запас, а командам перегруппироваться перед выходом.

* Третье не нужно. У нас вроде как сложность противника не переменная от города к городу, а постоянная на всю игру зависящая от настроек сессии сервера.

* Имеет место быть. Пока не научатся ставить вышку в приоритет выполнения, так и будут их поливать с бомбардировщиков и вертолётов.

В общем, предлагаю перейти на формат «По делу» во всех внутриигровых сообщениях. Как вы на это смотрите? (в частности Тимчерсен)

**Comment by Noart537** [comment]
Давай сократим описание основной миссии. Тотже штурм. Очень много текста. Достаточно будет. ×противник запросил подкрепления, приготовтесь к обороне.×

**Comment by Tourorist** [comment]
Согласен, сделаю.

По этой задаче я пока только делаю наброски у себя, вместо того чтобы выкладывать огрызки и мешать их с вашими промежуточными выпусками. В пятницу начну собирать все эти изменения на отдельной ветке, где можно будет их проверить.

Задача касается всех сообщений, но все кто захочет можете также как @Noart537 оставлять свои пожелания и по конкретным текстам, которые по ходу работы я конечно приму во внимание.

**Comment by Noart537** [comment]
Annex_Done_Right.Altis/mission/side/actions/sabotage.sqf
Заряд установлен. Приготовьтесь...

**Comment by Noart537** [comment]
@Tourorist Тебе выписать ссылки на файлы, в которых нужно редактировать текст в миссии?

**Comment by Tourorist** [comment]
@Noart537, не откажусь.

Если можно, собери их еще списком кнопочным, как наши с тобой задачи. Чтобы было на чем галочки ставить по ходу выполнения частей задачи.

**Comment by Noart537** [comment]
Хорошо. Сегодня-завтра сделаю тебе список.

**Comment by Noart537** [comment]
@Tourorist Тебе с сообщениями помочь?

**Comment by Tourorist** [comment]
Если до четверга не справлюсь сам то будешь помогать.

@Noart537, у тебя же пока вроде и своих задач хватает. :smile:

**Comment by Tourorist** [comment]
Применительно к <kbd>v3.5</kbd> всё готово.
