### ISSUE TITLE
Перевести журнал изменений

### ISSUE THREAD

**Issue by Tourorist** [TEHGAM/RW2#309]
Это послужит шагом на пути к переходу и началу выпусков миссии через сам Хаб.

То есть, надо изложить предысторию на английском и, в последствии, уже вести журнал параллельно на обоих языках. Русская версия будет в основном предназначаться для наших игроков, а английская версия будет держать двери открытыми для возможной помощи от иноязычных разработчиков (например, авторов скриптов).

**Comment by Tourorist** [comment]
Доработал и исправил ошибки.

В общем, @Noart537 молодец, вместо дословного перевода сделал правильные интерпретация по всем правилам локализации.

##### Заметки по моим конвенциям

| In English | По-русски
| :-----------: | :-----------:
| December 30, 2014  | 30 декабря 2014 г
| v0.01 | вер.0.01
| Virtual Ammobox System |  Снаряжении и экипировка

##### Также:
* Параметры ввода и сами кнопки клавиатуры отмечаем элементом <kbd>kbd</kbd>.
* Версии выпусков и скриптов пишем как код внутри квадратных [<code>скобок</code>].
* Все ссылки держим в абсолютном формате, чтобы при надобности было легко копировать.
* В правом столбике первой таблицы (текущий выпуск), удерживаем каждый заголовок на своей строке через <code>nbsp;</code> вместо обычного пробела между словами.

Посидим еще на этой задаче до конца недели, посмотрим если кто чего исправит, а в понедельник тогда поставим галочку.

**Comment by tym32167** [comment]
@Tourorist  Если все готово, то закрывай тикет.

**Comment by Tourorist** [comment]
Вы свои закрывайте не протестировав, я на своих сижу пока не проверю. :smile: 

Вообще пусть лучше у нас куча задач и PR висит чем мы будет всё проталкивать кабы как.

**Comment by tym32167** [comment]
А, ну смотри, как те удобней :smiley:

**Comment by Tourorist** [comment]
**Малые правки**
* В списке изменений к [<code>3.4</code>], добавил пропущенные <code>&lt;ul&gt;&lt;/ul&gt;</code> скобки.
* Затолкал подзаголовки текущего выпуска в  <code>&lt;sup&gt;&lt;/sup&gt;</code> элемент.
* Перешел на цифровой формат дат — DD.MM.YYYY (RU) и MM.DD.YYYY (EN).

**Comment by Tourorist** [comment]
* Добавил и перевел заметки к выпуску [<code>3.4.2</code>].

Сегодня уже задачу закрываем и ставим галочку на пути к пятерке.

**Comment by tym32167** [comment]
Ура ура :smiley:
