### ISSUE TITLE
Контроль стрельбы из бортовых орудий

### ISSUE THREAD

**Issue by Tourorist** [TEHGAM/RW2#322]
@ZeRoKoOl13 предлагает нам внедрить [эту систему](http://www.armaholic.com/page.php?id=27757) от Quicksilver-а.

Из описания следует, что этот скрипт позволяет пилотам вооруженных транспортных вертолетов (Гхостхок и Хурон) отключать — по надобности и без вопросов — возможность своим стрелкам палить из пулемётов.

**Comment by tym32167** [comment]
Звучит здорово. Я за.

**Comment by tym32167** [comment]
добавлю в рассылку @vosur

**Comment by Tourorist** [comment]
Я и сам не против.

* [Ссылка](http://www.tehgam.com/viewtopic.php?f=62&t=1605) на эту тему у нас на форуме.

**Comment by Noart537** [comment]
Добавил меню турелей, осталось его раскрасить.

**Comment by tym32167** [comment]
FIXED
