### ISSUE TITLE
Не убирается трава

### ISSUE THREAD

**Issue by Noart537** [TEHGAM/RW2#331]
В новом скрипте прорисовки, не работает кнопка "Нет", которая отключает траву.

**Comment by Tourorist** [comment]
@tym32167, если на Втором сейчас предыдущая версия, то можно при следующем рестарте залить текущую мастер копию чтобы проверить исправление этой ошибки?

**Comment by tym32167** [comment]
@Tourorist @Noart537 перевыложил миссию.

**Comment by Tourorist** [comment]
Проверил. У всех кто отозвался на просьбу проверить во время игры, меню работало полностью и без проблем.

**Comment by Noart537** [comment]
Закрываем?
