### ISSUE TITLE
На допзаданиях пропали ящики/ноутбуки

### ISSUE THREAD

**Issue by tym32167** [TEHGAM/RW2#332]
Невозможно теперь завершить допзадание, так как пропали ноутбуки. Задача высокого приоритета. Без решения этой проблемы миссию выложить не могу на сервер. РВ2 откатил к предыдущему состоянию.

@Noart537, назначаю на тебя.

**Comment by tym32167** [comment]
Конкретно залагали миссии ПВО и ШПИОНАЖ, другие тоже возможно лагают, не проверял.

**Comment by Tourorist** [comment]
Надо наверно [по инструкции](https://github.com/TEHGAM/RW2/blob/master/Annex_Done_Right.Altis/scripts/cleanup/repetitive_cleanup.sqf#L33) из скрипта сборки мусара, добавить эту линию к предметам на допзаданиях:
```
this setVariable["persistent",true];
```

В смысле, если они таким образом не прописаны в виде исключения, то я предполагаю что он их просто убирает сразу же после появления.

**Comment by Noart537** [comment]
Может пока вернуть скрипт старый по очистке? Дабы мисию пропустить. Останется только с травой разобраться.

**Comment by tym32167** [comment]
Надо убедиться, что проблема именно в этом. 
И лучше бы пофиксить это дело, а не откатывать скрипт. Иначе мы никогда его обновить не сможем. Но если пофиксить не удастся, то откатывай.

**Comment by Noart537** [comment]
Хорошо. В понедельник посмотрю в чем может быть проблемма.

**Comment by Noart537** [comment]
У нас в initServer. Оно по идее не работает.  Т.к. техника и тела очищаются, а тут стоит 0. в _79 этого нет. Как думайте стоит удалять?

[
    0, // seconds to delete dead bodies (0 means don't delete)
    0, // seconds to delete dead vehicles
    2*60, // seconds to delete dropped weapons
    30*60, // seconds to deleted planted explosives
    2*60 // seconds to delete dropped smokes/chemlights
  ] execVM "scripts\cleanup\repetitive_cleanup.sqf";

**Comment by Noart537** [comment]
По поводу респа еще файл есть. Тоже настроки респа и удаления от техники

https://github.com/TEHGAM/RW2/blob/master/Annex_Done_Right.Altis/module_performance/module_cleanup/config.sqf

**Comment by tym32167** [comment]
@Noart537 у меня пока нет времени так глубоко ковырять, ну и проверить это можно только опытным путем.

**Comment by tym32167** [comment]
@Tourorist @Noart537 Проверьте плиз кто может и закройте тикет, если все норм.

**Comment by Tourorist** [comment]
Ноутбуков не видел, но были первые два задания с ящиками. Один с зелёным брезентовым покрытием как VAS-овский (был в маленькой будке), другой квадратный из фанеры (стоял на втором этаже бункера). Меню подрыва на обоих работало как полагается.

Если будет время, попробую завтра до ноутбука доиграться.

**Comment by tym32167** [comment]
Ноутбуки или ящики значения не имеет, раз миссии выполнялись нормально, значит, проблема закрыта.
