### ISSUE TITLE
Переместить наградную технику с глаз долой

### ISSUE THREAD

**Issue by tym32167** [TEHGAM/RW2#334]
В соответствии с [предложением](http://www.tehgam.com/viewtopic.php?p=13312#p13312) делаю тикет. По моему, вполне здравая мысль. 
> Есть предложение перенести респ наградной техники куда-нибудь подольше от терминала с глаз долой. Сейчас получается, что выходя из терминала игрок видит перед собой не занятую (пока команда добирается с допзадания на базу) технику и берет ее без спроса. Думаю, что краж наградной техники в случае переноса респа станет меньше. А те кражи которые и будут, то на 100% умышленные, и уже не отмажешься типа я не знал и т.д.

Убрать технику предлагаю на поле рядом с респом БПА:
![1](https://cloud.githubusercontent.com/assets/610799/5814465/7d484c46-a0ad-11e4-8de0-6f5e2206ccab.png)

Необходимо:
 1. Определить, достаточно ли там места для наградной техники.
 2. Если достаточно, перетянуть наградные маркеры туда

@Tourorist, @Noart537, @vosur, ваше мнение по этому поводу. Кто против, кто нет? Если никто не против, то можно пускать тикет в производство.

**Comment by vosur** [comment]
Давайте лучше не технику перенесем, а сам респ, тогда действительно на сервере будет что-то новенькое.

**Comment by tym32167** [comment]
Перенос респа - задача довольно сложная. Это не просто маркер подвинуть, это надо спроектировать новое расположение всей техники + завязать это все скриптами. Думаю, подобное надо оставить для следующего выпуска миссии.

**Comment by Noart537** [comment]
Я за, давно уже предлагал.

**Comment by tym32167** [comment]
Ждем @Tourorist . Коли он не против, то, @Noart537, тебе это доверим.

**Comment by Noart537** [comment]
Давайте только ближе к концу недели. Старые надо доделать)

**Comment by tym32167** [comment]
Это не баг, да и вообще задача без приоритета, она терпит.В принципе, я на выходных арму себе поставлю снова и, может, сделаю это сам.

**Comment by Tourorist** [comment]
Делайте только бережно, пожалуйста. Не так как с переносом игроков в терминал было, когда сейчас после этого раз через раз персонажи появляются в скамейках и получают урон уже в первые секунды жизни, пока выкарабкиваются из них.

Вещи перемешаем и ставим на точные координаты используя ортографический вид, а в 3D редакторе проверяем корректность их начального направления и высоту при респе.

А так, идея конечно не плохая. @tym32167 в частных разговорах уже предлагал подобное.

**Comment by tym32167** [comment]
Ну вот и решено, @Noart537 назначу покамест на тебя.

**Comment by Noart537** [comment]
После 317 займусь

**Comment by Noart537** [comment]
Поставил тут, прямая местность и без деревьев и кустов.
![0](https://cloud.githubusercontent.com/assets/8770445/5833036/e387a7aa-a16f-11e4-8da9-f1a71686713c.png)
