### ISSUE TITLE
Список файлов для корректировки текста

### ISSUE THREAD

**Issue by Noart537** [TEHGAM/RW2#344]
### Основная
- [x] [regionCE.sqf](https://github.com/TEHGAM/RW2/blob/master/Annex_Done_Right.Altis/mission/main/region/regionCE.sqf)
- [x] [regionNE.sqf](https://github.com/TEHGAM/RW2/blob/master/Annex_Done_Right.Altis/mission/main/region/regionNE.sqf)
- [x] [regionNW.sqf](https://github.com/TEHGAM/RW2/blob/master/Annex_Done_Right.Altis/mission/main/region/regionNW.sqf)
- [x] [regionSE.sqf](https://github.com/TEHGAM/RW2/blob/master/Annex_Done_Right.Altis/mission/main/region/regionSE.sqf)
- [x] [regionSW.sqf](https://github.com/TEHGAM/RW2/blob/master/Annex_Done_Right.Altis/mission/main/region/regionSW.sqf)
<br />

##### Оборона точки
- [x] [AOdefend.sqf](https://github.com/TEHGAM/RW2/blob/master/Annex_Done_Right.Altis/mission/main/AOdefend.sqf)
<br />

##### Штурмовик
- [x] [CAS.sqf](https://github.com/TEHGAM/RW2/blob/master/Annex_Done_Right.Altis/mission/main/CAS.sqf)
- [x] [fn_rewardPlusHintJet.sqf](https://github.com/TEHGAM/RW2/blob/master/Annex_Done_Right.Altis/functions/fn_rewardPlusHintJet.sqf)

### Дополнительные
- [x] [sabotage.sqf](https://github.com/TEHGAM/RW2/blob/master/Annex_Done_Right.Altis/mission/side/actions/sabotage.sqf)
- [x] [smSwitch.sqf](https://github.com/TEHGAM/RW2/blob/master/Annex_Done_Right.Altis/mission/side/actions/smSwitch.sqf)
- [x] [HQcoast.sqf](https://github.com/TEHGAM/RW2/blob/master/Annex_Done_Right.Altis/mission/side/missions/HQcoast.sqf)
- [x] [HQfia.sqf](https://github.com/TEHGAM/RW2/blob/master/Annex_Done_Right.Altis/mission/side/missions/HQfia.sqf)
- [x] [HQind.sqf](https://github.com/TEHGAM/RW2/blob/master/Annex_Done_Right.Altis/mission/side/missions/HQind.sqf)
- [x] [HQresearch.sqf](https://github.com/TEHGAM/RW2/blob/master/Annex_Done_Right.Altis/mission/side/missions/HQresearch.sqf)
- [x] [destroyUrban.sqf](https://github.com/TEHGAM/RW2/blob/master/Annex_Done_Right.Altis/mission/side/missions/destroyUrban.sqf)
- [x] [priorityAA.sqf](https://github.com/TEHGAM/RW2/blob/master/Annex_Done_Right.Altis/mission/side/missions/priorityAA.sqf)
- [x] [priorityARTY.sqf](https://github.com/TEHGAM/RW2/blob/master/Annex_Done_Right.Altis/mission/side/missions/priorityARTY.sqf)
- [x] [secureChopper.sqf](https://github.com/TEHGAM/RW2/blob/master/Annex_Done_Right.Altis/mission/side/missions/secureChopper.sqf)
- [x] [secureRadar.sqf](https://github.com/TEHGAM/RW2/blob/master/Annex_Done_Right.Altis/mission/side/missions/secureRadar.sqf)

##### Исход задания
- [x] [fn_SMhintSUCCESS.sqf](https://github.com/TEHGAM/RW2/blob/master/Annex_Done_Right.Altis/functions/fn_SMhintSUCCESS.sqf)
- [x] [fn_SMhintFAIL.sqf](https://github.com/TEHGAM/RW2/blob/master/Annex_Done_Right.Altis/functions/fn_SMhintFAIL.sqf)

**Comment by Tourorist** [comment]
Спасибо.

> «Заряд установлен. Приготовьтесь...» — наверно лучше написать что-то вроде «Уходим!»
У каждой допки одни и те же три сообщения крутятся:
* «Оперативный боезапас захвачен. C-4 активирован! 5 секунд до детонации.»
* «Оружие боевиков перехвачено. Взрывчатка установлена! 5 секунд до взрыва.»
* «Боезапас террористов захвачен. Заряд установлен! 5 секунд до взрыва.»

Их видно, но того короткого что в саботаже висит, что-то в игре не припомню.

**Comment by Noart537** [comment]
когда закладываешь заряд, в файле mission прописано обращение к файлу sabotage.sqf
```sqf
class Item83
		{
			position[]={-10792.91,0,-4209.4521};
			id=151;
			side="EMPTY";
			vehicle="Land_PaperBox_open_full_F";
			skill=0.60000002;
			text="crate1";
			init="this addAction [""<t color='#ffff00'>Set C4 Charge</t>"",""mission\side\actions\sabotage.sqf"",[],21,true,true,"""",'((vehicle player) == player) && ((player distance _target) < 5)']; this allowDamage false;";
		};
		class Item84
		{
			position[]={-10792.871,0,-4205.4326};
			id=152;
			side="EMPTY";
			vehicle="Land_PaperBox_closed_F";
			skill=0.60000002;
			text="crate2";
			init="this addAction [""<t color='#ffff00'>Set C4 Charge</t>"",""mission\side\actions\sabotage.sqf"",[],21,true,true,"""",'((vehicle player) == player) && ((player distance _target) < 5)']; this allowDamage false;";
		};
```

**Comment by Noart537** [comment]
Вру) в начале миссии идет обращение к этому файлу)
```sqf
init="this allowDamage false; this addAction [""<t color='#ffff00'>Захватить ПУ и установить подрывной заряд</t>"",""mission\side\actions\sabotage.sqf"",[],21,true,true,"""",'((vehicle player) == player) && ((player distance _target) < 5)'];";
```

**Comment by Tourorist** [comment]
Сообщения из ряда «Важная цель» теперь будут выходить под заголовком «Внимание».

**Comment by Tourorist** [comment]
Осталось только допкидоделать. Попробую доделать сегодня вечером или завтра до полудня. 

Если не получится то буду дёргать @Noart537, раз уж он уверен что помимо помощи еще и свои успеет вовремя сделать.

**Comment by Tourorist** [comment]
Надо теперь на чисто техническом уровне проверить работает ли всё это, как и прежде, а то мало-ли задел что.

**Comment by Tourorist** [comment]
Местно вроде всё работает. Будем надеяться что никаких [других бомб](http://i.imgur.com/wmlCPQn.gifv) случайно не разбросал.

**Comment by a11archer** [comment]
А ветка какая? Основная master branch?

**Comment by Tourorist** [comment]
Да, это всё уже в мастере.
